# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 08:14
from __future__ import unicode_literals

import deploy.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileRollback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(default=None, max_length=244, verbose_name='\u8fdc\u7a0b\u4e3b\u673a')),
                ('cur_path', models.CharField(max_length=244)),
                ('bak_path', models.CharField(max_length=244)),
                ('file_tag', models.CharField(max_length=244, unique=True, verbose_name='\u6587\u4ef6\u6807\u7b7e')),
                ('remark', models.TextField(blank=True, max_length=50, verbose_name='\u5907\u6ce8')),
                ('is_group', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'default_permissions': (),
                'verbose_name': '\u6587\u4ef6\u5907\u4efd\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=244, verbose_name='\u8fdc\u7a0b\u4e3b\u673a')),
                ('file_path', models.FileField(upload_to=deploy.models.file_upload_dir_path, verbose_name='\u6587\u4ef6\u4e0a\u4f20')),
                ('remote_path', models.CharField(max_length=244, verbose_name='\u8fdc\u7a0b\u8def\u5f84')),
                ('file_tag', models.CharField(max_length=244, unique=True, verbose_name='\u6587\u4ef6\u6807\u7b7e')),
                ('remark', models.TextField(blank=True, max_length=50, verbose_name='\u5907\u6ce8')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
                'verbose_name': '\u6587\u4ef6\u4e0a\u4f20\u7ba1\u7406',
                'permissions': (('view_filemanage', '\u67e5\u770b\u6587\u4ef6\u7ba1\u7406'), ('edit_fileupload', '\u7ba1\u7406\u6587\u4ef6\u4e0a\u4f20'), ('edit_filedownload', '\u7ba1\u7406\u6587\u4ef6\u4e0b\u8f7d')),
            },
        ),
        migrations.CreateModel(
            name='ModuleUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='\u6a21\u5757\u540d\u79f0')),
                ('module', models.CharField(max_length=50, unique=True, verbose_name='\u8c03\u7528\u6a21\u5757')),
                ('upload_path', models.FileField(blank=True, upload_to=deploy.models.user_dir_path, verbose_name='\u6a21\u5757\u4e0a\u4f20')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='\u5907\u6ce8')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
                'verbose_name': 'Salt\u6a21\u5757',
                'verbose_name_plural': 'Salt\u6a21\u5757\u7ba1\u7406',
                'permissions': (('edit_module', '\u7ba1\u7406Salt\u6a21\u5757'),),
            },
        ),
        migrations.CreateModel(
            name='SaltGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=80, unique=True, verbose_name='Salt\u5206\u7ec4')),
                ('groupname', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'default_permissions': (),
                'verbose_name': 'Salt\u5206\u7ec4',
                'verbose_name_plural': 'Salt\u5206\u7ec4\u7ba1\u7406',
                'permissions': (('edit_saltgroup', '\u7ba1\u7406Salt\u4e3b\u673a\u5206\u7ec4'),),
            },
        ),
        migrations.CreateModel(
            name='SaltHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=80, unique=True, verbose_name='\u4e3b\u673a\u540d\u79f0')),
                ('alive', models.BooleanField(default=False, verbose_name='\u8fde\u901a\u72b6\u6001')),
                ('alive_time_last', models.DateTimeField(auto_now=True)),
                ('alive_time_now', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False, verbose_name='\u662f\u5426\u52a0\u5165salt\u7ba1\u7406')),
            ],
            options={
                'default_permissions': (),
                'verbose_name': 'Salt\u4e3b\u673a\u6388\u6743',
                'verbose_name_plural': 'Salt\u4e3b\u673a\u6388\u6743\u7ba1\u7406',
                'permissions': (('view_deploy', '\u67e5\u770b\u4e3b\u673a\u90e8\u7f72'), ('edit_deploy', '\u7ba1\u7406\u4e3b\u673a\u90e8\u7f72'), ('edit_salthost', '\u7ba1\u7406Salt\u4e3b\u673a')),
            },
        ),
        migrations.AddField(
            model_name='saltgroup',
            name='minions',
            field=models.ManyToManyField(related_name='salt_host_set', to='deploy.SaltHost', verbose_name='Salt\u4e3b\u673a'),
        ),
    ]
