# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='\u673a\u67dc\u7f16\u53f7')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u673a\u67dc',
                'verbose_name_plural': '\u673a\u67dc',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=255, null=True, verbose_name='\u4e3b\u673aDNS\u540d\u79f0')),
                ('kernel', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7cfb\u7edf\u5185\u6838')),
                ('kernel_release', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7cfb\u7edf\u5185\u6838\u7248\u672c')),
                ('virtual', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u8bbe\u5907\u7c7b\u578b')),
                ('host', models.CharField(max_length=255, null=True, verbose_name='\u4e3b\u673a\u540d')),
                ('osrelease', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf\u7248\u672c')),
                ('saltversion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Salt\u7248\u672c')),
                ('osfinger', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7cfb\u7edf\u6307\u7eb9')),
                ('os_family', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7cfb\u7edf\u7c7b\u578b')),
                ('num_gpus', models.IntegerField(blank=True, null=True, verbose_name='GPU\u6570\u91cf')),
                ('system_serialnumber', models.CharField(blank=True, max_length=255, null=True, verbose_name='SN\u53f7')),
                ('cpu_model', models.CharField(blank=True, max_length=255, null=True, verbose_name='CPU\u578b\u53f7')),
                ('productname', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4ea7\u54c1\u540d\u79f0')),
                ('osarch', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7cfb\u7edf\u67b6\u6784')),
                ('cpuarch', models.CharField(blank=True, max_length=255, null=True, verbose_name='CPU\u67b6\u6784')),
                ('os', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf')),
                ('mem_total', models.IntegerField(blank=True, null=True, verbose_name='\u5185\u5b58\u5927\u5c0f')),
                ('num_cpus', models.IntegerField(blank=True, null=True, verbose_name='CPU\u6570\u91cf')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u4e3b\u673a',
                'verbose_name_plural': '\u4e3b\u673a',
            },
        ),
        migrations.CreateModel(
            name='HostIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='IP\u5730\u5740')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('host', models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='CMDB.Host', verbose_name='\u4e3b\u673a')),
            ],
            options={
                'verbose_name': '\u4e3b\u673aIP',
                'verbose_name_plural': '\u4e3b\u673aIP',
            },
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u673a\u623f\u540d\u79f0')),
                ('bandwidth', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u673a\u623f\u5e26\u5bbd')),
                ('phone', models.CharField(max_length=255, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('linkman', models.CharField(max_length=255, null=True, verbose_name='\u8054\u7cfb\u4eba')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u673a\u623f\u5730\u5740')),
                ('concat_email', models.EmailField(blank=True, default=b'', max_length=254, null=True, verbose_name='\u8054\u7cfb\u90ae\u7bb1')),
                ('network', models.TextField(blank=True, null=True, verbose_name='IP\u5730\u5740\u6bb5')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u673a\u623f',
                'verbose_name_plural': '\u673a\u623f',
            },
        ),
        migrations.CreateModel(
            name='IDCLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u540d\u79f0')),
                ('comment', models.TextField(verbose_name='\u63cf\u8ff0')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u673a\u623f\u7b49\u7ea7',
                'verbose_name_plural': '\u673a\u623f\u7b49\u7ea7',
            },
        ),
        migrations.CreateModel(
            name='ISP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u540d\u79f0')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': 'ISP\u7c7b\u578b',
                'verbose_name_plural': 'ISP\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='\u673a\u67b6\u540d\u79f0')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMDB.Cabinet', verbose_name='\u673a\u67dc')),
            ],
            options={
                'verbose_name': '\u673a\u67b6',
                'verbose_name_plural': '\u673a\u67b6',
            },
        ),
        migrations.AddField(
            model_name='idc',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMDB.ISP', verbose_name='ISP\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='idc',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMDB.IDCLevel', verbose_name='\u673a\u623f\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='host',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CMDB.Rack', verbose_name='\u673a\u67b6'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMDB.IDC', verbose_name='\u673a\u623f'),
        ),
    ]
